GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_TOP_TIMEOFDAY,
    false
);
GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_TOP_HEROES,
    false
);
GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_ACTION_MINIMAP,
    false
);
GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_ACTION_PANEL,
    false
);
GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_INVENTORY_PANEL,
    false
);
GameUI.SetDefaultUIEnabled(
    DotaDefaultUIElement_t.DOTA_DEFAULT_UI_INVENTORY_SHOP,
    false
);
